<?php
function News_menu() {
  $items = array();
  $items['generate_words'] = array(
    'title' => 'Generate Words',
    'page callback' => 'get_words',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  );
  $items['which_website'] = array(
    'title' => 'Pick A Website',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['grab_website/%'] = array(
    'title' => 'Grab Website',
    'page callback' => 'grab_website',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
  return $items;
}

function get_words() {
  $titleWordArray = [];
  $descriptionWordArray = [];
  $sourceArray = array(
    'breitbart-news',
    'buzzfeed',
    'daily-mail',
    'mirror',
    'metro',
    'mashable'
  );

  // for ($i=0; $i<1; $i++) {
  for ($i=0; $i<count($sourceArray); $i++) {
    $news = curl_init();
    curl_setopt_array($news, array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => 'https://newsapi.org/v1/articles?source='.$sourceArray[$i].'&sortBy=latest&apiKey=ccd4623de5dd47dd9c48798e310b4e34'
    ));
    $articles = curl_exec($news);
    curl_close($news);

    $recent_news = json_decode($articles);
    if ($recent_news->status === 'ok') {

      $articleNumber = count($recent_news->articles);
      for ($j=0;$j<$articleNumber;$j++){
        $newArticleArray[] = [];
        $url = $recent_news->articles[$j]->url;
        $exists = db_query("SELECT * FROM raw_words WHERE url = '{$url}'");
        $record = $exists->fetchAssoc();

        if(!$record) {
          $phrase_string = '';
          foreach ($recent_news->articles[$j] as $key => $val) {
            if (is_null($val)) {
              $val = '';
            }
            $val = str_replace("'","`",$val);
            $val = preg_replace('/[^A-Za-z0-9\s]/', '', $val);
            $val = strtolower($val);
            if($key === 'title') {
              $oneWordArray = explode(" ", $val);
              foreach($oneWordArray as $key => $val){
                $titleWordArray[] = [$key, $val];
                $part_of_speech_curl = curl_init();
                curl_setopt_array($part_of_speech_curl, array(
                CURLOPT_RETURNTRANSFER => 1,
                CURLOPT_URL => 'https://api.datamuse.com/words?sp='.$val.'&md=p'
                ));
                $part_of_speech = curl_exec($part_of_speech_curl);
                $part_of_speech = json_decode($part_of_speech);
                $part_of_speech = $part_of_speech[0]->tags[0];
                $phrase_string .= $part_of_speech . ',';
                db_query("INSERT INTO raw_words (word,part_of_speech,position,url) VALUES ('{$val}','{$part_of_speech}', '{$key}', '{$url}');");
              }
            }
          }
          db_query("INSERT INTO phrase_arrays (phrase_array) VALUES ('{$phrase_string}')");
        }
      }
    }
  }

  return "Ready to browse!";

}


function site_form() {
  $form['site'] = array(
    '#title' => 'http://',
    '#type' => 'textfield',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Randomize It',
  );
  return $form;
}

function site_form_submit($form, &$form_state) {
  $_SESSION['site'] = 'http://'.$form_state['values']['site'];
  $form_state['redirect'] = 'grab_website/'.$form_state['values']['site'];
}



function grab_website($site) {
  getNouns();
  getVerbs();
  getAdjs();
  getAdvs();
  getFiller();
  getPhrases();
  $testArray = ['adj','n','','v','adv','n','n'];
  $full_site = file_get_contents('http://'.$site);
  $doc = new DOMDocument();
  $doc->loadHTML($full_site);
  $h1s = $doc->getElementsByTagName('h1');
  $h2s = $doc->getElementsByTagName('h2');
  $h3s = $doc->getElementsByTagName('h3');
  $ps = $doc->getElementsByTagName('p');
  $lis = $doc->getElementsByTagName('li');
  $as = $doc->getElementsByTagName('a');
  foreach ($h1s as $h1) {
    $h1->nodeValue = ucwords(randomPhrase());
  }
  foreach ($h2s as $h2) {
    $h2->nodeValue = ucwords(randomPhrase());
  }
  foreach ($h3s as $h3) {
    $h3->nodeValue = ucwords(randomPhrase());
  }
  foreach ($ps as $p) {
      $p->nodeValue = ucfirst(randomPhrase());
  }
  foreach ($lis as $li) {
      $li->nodeValue = ucfirst(randomPhrase());
  }
  foreach ($as as $a) {
      $href = $a->getAttribute('href');
      $href = str_replace('http://', '', $href);
      $href = str_replace('https://', '', $href);
      if ($href[0] == '/') {
        $href = $site.$href;
      } else {
        $href = $href;
      }
      $a->setAttribute('href', $href);
      $a->nodeValue = ucfirst(randomPhrase());
  }
  return $doc->saveHTML();
}

function randomWord($wordType) {
  if($wordType == 'n'){
    return $_SESSION['nouns'][array_rand($_SESSION['nouns'])];
  }
  if($wordType == 'v'){
    return $_SESSION['verbs'][array_rand($_SESSION['verbs'])];
  }
  if($wordType == 'adv'){
    return $_SESSION['advs'][array_rand($_SESSION['advs'])];
  }
  if($wordType == 'adj'){
    return $_SESSION['adjs'][array_rand($_SESSION['adjs'])];
  }
  if($wordType == ''){
    return $_SESSION['filler'][array_rand($_SESSION['filler'])];
  }
  else {
    return $_SESSION['filler'][array_rand($_SESSION['filler'])];
  }
}

function randomPhrase() {
  $phrase = '';
  $phraseArray = randomPhraseArray();
    for($i=0;$i<count($phraseArray);$i++){
      $phrase .= randomWord($phraseArray[$i]) . ' ';
    }
  return $phrase;
}

function randomPhraseArray() {
  return explode(',',$_SESSION['phrases'][array_rand($_SESSION['phrases'])]);
}

function getNouns() {
  $query = db_query("SELECT * FROM raw_words WHERE part_of_speech = 'n'");
  $nouns = [];
  foreach($query as $noun) {
    $nouns[] = $noun->word;
  }
  $_SESSION['nouns'] = $nouns;
}

function getVerbs() {
  $query = db_query("SELECT * FROM raw_words WHERE part_of_speech = 'v'");
  $verbs = [];
  foreach($query as $verb) {
    $verbs[] = $verb->word;
  }
  $_SESSION['verbs'] = $verbs;
}

function getAdjs() {
  $query = db_query("SELECT * FROM raw_words WHERE part_of_speech = 'adj'");
  $adjs = [];
  foreach($query as $adj) {
    $adjs[] = $adj->word;
  }
  $_SESSION['adjs'] = $adjs;
}

function getAdvs() {
  $query = db_query("SELECT * FROM raw_words WHERE part_of_speech = 'adv'");
  $advs = [];
  foreach($query as $adv) {
    $advs[] = $adv->word;
  }
  $_SESSION['advs'] = $advs;
}

function getFiller() {
  $query = db_query("SELECT * FROM raw_words WHERE part_of_speech = ''");
  $fillers = [];
  foreach($query as $filler) {
    $fillers[] = $filler->word;
  }
  $_SESSION['filler'] = $fillers;
}

function getPhrases() {
  $query = db_query("SELECT * FROM phrase_arrays");
  $phrases = [];
  foreach($query as $phrase) {
    $phrases[] = $phrase->phrase_array;
  }
  $_SESSION['phrases'] = $phrases;
}
